// Dynamic Gallery Image Loader
// Automatically loads images from public/images/gallery/ folders
// Supports .webp, .jpg, .jpeg, .png files
// For before/after pairs, name them: image-name.webp and image-name-before.webp
// This file is auto-generated by scripts/generate-gallery-images.js

import type { GalleryImage } from './galleryData';

// Category folder mapping (folder name -> category id)
const categoryFolders = ['ppf', 'ceramic', 'graphene', 'detailing', 'interior', 'exterior', 'wash', 'polishing', 'rust-protection', 'alloy', 'underbody', 'engine-ac', 'headlight', 'restoration'] as const;
type Category = typeof categoryFolders[number];

// Manual image list - Auto-generated from public/images/gallery/
const manualImageList: { path: string; category: Category }[] = [
  { path: '/images/gallery/alloy/1-before.webp', category: 'alloy' },
  { path: '/images/gallery/alloy/1.webp', category: 'alloy' },
  { path: '/images/gallery/engine-ac/1-before.webp', category: 'engine-ac' },
  { path: '/images/gallery/engine-ac/1.webp', category: 'engine-ac' },
  { path: '/images/gallery/restoration/1.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/10.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/11.JPG', category: 'restoration' },
  { path: '/images/gallery/restoration/12.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/13.jpg', category: 'restoration' },
  { path: '/images/gallery/restoration/14.jpg', category: 'restoration' },
  { path: '/images/gallery/restoration/15.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/16.jpg', category: 'restoration' },
  { path: '/images/gallery/restoration/17.jpg', category: 'restoration' },
  { path: '/images/gallery/restoration/18.jpg', category: 'restoration' },
  { path: '/images/gallery/restoration/2.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/3.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/4.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/5.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/6.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/7.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/8.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/9.webp', category: 'restoration' },
];

interface ImageFile {
  path: string;
  url: string;
  filename: string;
  category: Category;
}

function galleryImages(): GalleryImage[] {
  const images: GalleryImage[] = [];
  let id = 1;

  // Process each image file from manual list
  const files: ImageFile[] = [];

  manualImageList.forEach(({ path, category }) => {
    const filename = path.split('/').pop() || '';
    files.push({ path, url: path, filename, category });
  });

  // Group by category
  const categoryFiles: Record<string, ImageFile[]> = {};
  files.forEach(file => {
    if (!categoryFiles[file.category]) {
      categoryFiles[file.category] = [];
    }
    categoryFiles[file.category].push(file);
  });

  // Process each category and pair before/after images
  Object.entries(categoryFiles).forEach(([category, items]) => {
    const pairs = new Map<string, { before?: string; after?: string }>();

    items.forEach(({ url, filename }) => {
      // Remove extension
      const nameWithoutExt = filename.replace(/\.(webp|jpg|jpeg|png)$/i, '');
      // Check if it's a "before" image
      const isBefore = /-before$|-b4$/i.test(nameWithoutExt);
      // Get base name (remove -before suffix)
      const baseName = isBefore
        ? nameWithoutExt.replace(/-before$|-b4$/i, '')
        : nameWithoutExt;

      if (!pairs.has(baseName)) {
        pairs.set(baseName, {});
      }

      const pair = pairs.get(baseName)!;
      if (isBefore) {
        pair.before = url;
      } else {
        pair.after = url;
      }
    });

    // Create GalleryImage objects from pairs
    pairs.forEach((pair, name) => {
      const mainImage = pair.after || pair.before;
      if (!mainImage) return;

      images.push({
        id: id++,
        src: mainImage,
        before: pair.before && pair.after ? pair.before : undefined,
        alt: formatAltText(name),
        category: category as Category,
      });
    });
  });

  return images;
}

function formatAltText(filename: string): string {
  // Convert file-name to "File Name"
  return filename
    .replace(/-/g, ' ')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

// Export the dynamically loaded images
export const dynamicGalleryImages: GalleryImage[] = galleryImages();

// Debug: Log the generated images to console
if (typeof window !== 'undefined') {
  console.log('Gallery Images:', dynamicGalleryImages);
  console.log('Dynamic Gallery Length:', dynamicGalleryImages.length);
}

// Fallback images if no images found in folders
export const fallbackGalleryImages: GalleryImage[] = [
  {
    id: 101,
    src: 'https://images.unsplash.com/photo-1619405399517-d7fce0f13302?w=800&q=80',
    before: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80',
    alt: 'PPF Installation',
    category: 'ppf',
  },
  {
    id: 102,
    src: 'https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9?w=800&q=80',
    alt: 'Ceramic Coating',
    category: 'ceramic',
  },
  {
    id: 103,
    src: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
    before: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    alt: 'Graphene Coating Transformation',
    category: 'graphene',
  },
  {
    id: 104,
    src: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=800&q=80',
    alt: 'Premium Interior Detailing',
    category: 'interior',
  },
  {
    id: 105,
    src: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
    alt: 'Luxury Exterior Polishing',
    category: 'polishing',
  },
  {
    id: 106,
    src: 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=800&q=80',
    alt: 'Professional Car Wash',
    category: 'wash',
  },
  {
    id: 107,
    src: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80',
    alt: 'Complete Restoration Project',
    category: 'restoration',
  },
  {
    id: 108,
    src: 'https://images.unsplash.com/photo-1601362840469-51e4d8d59085?w=800&q=80',
    alt: 'Headlight Restoration',
    category: 'headlight',
  },
  {
    id: 109,
    src: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',
    alt: 'Luxury Alloy Treatment',
    category: 'alloy',
  },
  {
    id: 110,
    src: 'https://images.unsplash.com/photo-1619405399517-d7fce0f13302?w=800&q=80',
    alt: 'Detailing Excellence',
    category: 'detailing',
  }
];

// Use dynamic images if found in folders, otherwise fall back to placeholders
export const autoGalleryImages = dynamicGalleryImages.length > 0
  ? dynamicGalleryImages
  : fallbackGalleryImages;
