// Auto-generated by scripts/generate-gallery-images.js

import type { GalleryImage } from './galleryData';

const categoryFolders = ['ppf', 'ceramic', 'detailing', 'interior','wash', 'restoration'] as const;

type Category = typeof categoryFolders[number];

const manualImageList: { path: string; category: Category }[] = [
  { path: '/images/gallery/ceramic/12.webp', category: 'ceramic' },
  { path: '/images/gallery/ceramic/14.webp', category: 'ceramic' },
  { path: '/images/gallery/ceramic/3.webp', category: 'ceramic' },
  { path: '/images/gallery/ceramic/9.webp', category: 'ceramic' },
  { path: '/images/gallery/detailing/16.webp', category: 'detailing' },
  { path: '/images/gallery/detailing/17.webp', category: 'detailing' },
  { path: '/images/gallery/detailing/18.webp', category: 'detailing' },
  { path: '/images/gallery/detailing/8.webp', category: 'detailing' },
  { path: '/images/gallery/interior/1.webp', category: 'interior' },
  { path: '/images/gallery/interior/5.webp', category: 'interior' },
  { path: '/images/gallery/ppf/10.webp', category: 'ppf' },
  { path: '/images/gallery/ppf/11.webp', category: 'ppf' },
  { path: '/images/gallery/ppf/13.webp', category: 'ppf' },
  { path: '/images/gallery/ppf/2.webp', category: 'ppf' },
  { path: '/images/gallery/ppf/6.webp', category: 'ppf' },
  { path: '/images/gallery/restoration/15.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/19.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/20.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/4.webp', category: 'restoration' },
  { path: '/images/gallery/restoration/7.webp', category: 'restoration' },
];

const BEFORE_REGEX = /-before$|-b4$/i;

function galleryImages(): GalleryImage[] {
  const images: GalleryImage[] = [];
  let id = 1;

  const categoryFiles: Record<string, typeof manualImageList> = {};

  for (const image of manualImageList) {
    (categoryFiles[image.category] ??= []).push(image);
  }

  for (const [category, items] of Object.entries(categoryFiles)) {
    const pairs = new Map<string, { before?: string; after?: string }>();

    for (const { path } of items) {
      const filename = path.split('/').pop() ?? '';
      const name = filename.replace(/\.(webp|jpg|jpeg|png)$/i, '');

      const isBefore = BEFORE_REGEX.test(name);
      const baseName = isBefore
        ? name.replace(BEFORE_REGEX, '')
        : name;

      const pair = pairs.get(baseName) ?? {};

      if (isBefore) {
        pair.before = path;
      } else {
        pair.after = path;
      }

      pairs.set(baseName, pair);
    }

    for (const [name, pair] of pairs) {
      const src = pair.after ?? pair.before;

      if (!src) continue;

      images.push({
        id: id++,
        src,
        before:
          pair.before && pair.after
            ? pair.before
            : undefined,
        alt: formatAltText(name),
        category: category as Category,
      });
    }
  }

  return images;
}

function formatAltText(filename: string): string {
  return filename
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}

export const dynamicGalleryImages = galleryImages();

export const fallbackGalleryImages: GalleryImage[] = [
  // Your fallback images...
];

export const autoGalleryImages =
  dynamicGalleryImages.length
    ? dynamicGalleryImages
    : fallbackGalleryImages;
